### ISSUE TITLE
consistent colors in Agent

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#101]
make colors in agent top bars, emboss and buttons consistent with each other and colors in HTML apps

**Comment by GregTurner** [comment]
I need more info please

**Comment by dickhardt** [comment]
the blue highlight for the buttons is completely different tone than the blue in the title -- jarring -- have designer review colors

**Comment by GregTurner** [comment]
sent over to Simon

**Comment by GregTurner** [comment]
fixed

**Comment by dickhardt** [comment]
Not in 0.15

The color of the embossed Agent looks odd.

The color of a pressed button clashes with the color of the title bar color.

**Comment by GregTurner** [comment]
Colour was from designer.
