### ISSUE TITLE
confirmation screen disappears after selecting to delete an app's Anytime Authorization

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#102]

**Comment by GregTurner** [comment]
Is this where you tapping outside of the confirmation dialogue box?  Similar to the problem on the Settings->Reset dialogue?

**Comment by dickhardt** [comment]
yes -- try using the Agent on the phone -- it acts pretty flacky

On Thu, Mar 14, 2013 at 5:18 PM, GregTurner notifications@github.comwrote:

> Is this where you tapping outside of the confirmation dialogue box?
> Similar to the problem on the Settings->Reset dialogue?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dickhardt/A2P3_agent/issues/102#issuecomment-14937451
> .

## 

-- Dick

**Comment by GregTurner** [comment]
fixed in 1.3
