### ISSUE TITLE
clicking buttons does not always invoke action

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#104]
eg. clicking "review anytime authorizations" -- sometimes the screen will show it was clicked, but it did not go to the screen

**Comment by GregTurner** [comment]
setting $.mobile.buttonMarkup.hoverDelay = 0; should fix this... test on phone.  may have to switch event from 'tap' to 'click.

**Comment by GregTurner** [comment]
fixed.
