### ISSUE TITLE
subsequent invocations to Review Anytime Authorizations do not get new data

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#105]
Data is not updated. No calls are logged to the servers.

**Comment by GregTurner** [comment]
can't reproduce in browser agent... need to test on phone.

**Comment by GregTurner** [comment]
Still having trouble reproducing.  When you say subsequent invocations, you mean you did:

Home->Review...->Home->Review...?

And on the second Review no calls were made?

**Comment by dickhardt** [comment]
I just tested it and it seems to be making the calls now

The time still shows "a few seconds ago" though
