### ISSUE TITLE
Agent reset targets as.local when selecting prod (default)

### ISSUE THREAD

**Issue by watkinspd** [dickhardt/A2P3_agent#106]
The agent reset button is slow/clunky on loading and when it does come up and you press the last button (default) the agent sometimes is set to as.local.a2p3 in stead of prod.

Causes a registration error.

Agen v1.3

I have to try to reset a couple of times before it winds up being reset against prod.

Also suggest the default button move to the top of the list with cancel at the bottom of the list.

**Comment by GregTurner** [comment]
fixed.

Except the slow a clunky animation... not much I can do except turn it off.  please advise.
