### ISSUE TITLE
change QR reader to pull http:// codes w/ ?json=true added to get request and state values

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#23]
This is not implemented in the sample app

**Comment by GregTurner** [comment]
Hmmm... so I append json=true like so:
http://localhost:8080/QR/DZiVzk3mEt8_nE3BP2gyOA?json=true

But still gives me back the HTML with the meta refresh tag.  :(

**Comment by dickhardt** [comment]
That would be a bug. Let me get on it. Sorry.

**Comment by dickhardt** [comment]
fixed
