### ISSUE TITLE
Agent does not seem to be using the new Agent Request 

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#24]

**Comment by GregTurner** [comment]
New Agent Request?  Elaborate please...

**Comment by dickhardt** [comment]
load <your-machine-running-sample-app:/login/direct

This should invoke the agent with a new agent request asking for email, si, people details and health care -? but is asking for ability to verify admin access and health

Does it for me, does it for Peter. 

/login/backdoor 

has same Agent Request and works

**Comment by GregTurner** [comment]
Thanks, that gives me enough to troubleshoot.

**Comment by GregTurner** [comment]
fixed.
