### ISSUE TITLE
Agent displays home page before displaying passcode page

### ISSUE THREAD

**Issue by watkinspd** [dickhardt/A2P3_agent#25]
When the agent is being invoked from direct login on phone you can see the home page displayed for a few second before you see the passcode input screen.  Doesn't feel right, should go straight to passcode in that case.

**Comment by GregTurner** [comment]
Agent Load
Home
Lag
Passcode

Look into event ondeviceready

**Comment by GregTurner** [comment]
I think I fixed it, but I want to test on an older device to make sure...
