### ISSUE TITLE
Scanning login QR code does not load QR

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#29]
URL in QR code is http://bank.a2p3.net/QR/xxxxxx or http://bank.a2p3.net/newQR/xxxxxxxx

No request is made for URL

request should be:

http://bank.a2p3.net/newQR/xxxxxxxx?json=true

**Comment by GregTurner** [comment]
This is odd.  Request is made and works from when running agent in browser.  Need to debug on iphone Monday.

**Comment by GregTurner** [comment]
fixed.
