### ISSUE TITLE
Link to setup.a2p3.net from unenrolled page

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#35]
When first running the Agent, link to enroll directly at Setup should be shown in addition to "Scan Enrollment QR Code"

perhaps a label of:

"Enroll Agent Directly"

**Comment by GregTurner** [comment]
done

**Comment by dickhardt** [comment]
Use setup value from the Settings page ... otherwise it is the wrong host when clicked

**Comment by dickhardt** [comment]
my bad, does work -- the save button at the bottom of settings is hard to remember to use :( -- I click down and then navigate away
