### ISSUE TITLE
Agent does not enroll when first oppened with /enroll call

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#36]
Steps:

install agent (do not open)

goto setup.a2p3.net, register, enroll iOS agent, on phone

Agent is loaded, but prompts to scan enrollment QR code

**Comment by GregTurner** [comment]
confirmed except for the last sentance.  I get user not found when trying to enroll from a2p3.net://enroll... still tracing

**Comment by dickhardt** [comment]
I have gotten some of those errors as well. Adding instrumentation to figure out what is going on.

**Comment by GregTurner** [comment]
Same here...

**Comment by GregTurner** [comment]
I seem to always get the same enroll code, e.g., 7_yCQw....

**Comment by dickhardt** [comment]
If it was already generated, it is a value in the session that is used. 

I might need to clear it somewhere to ensure a new one is generated.

enroll on the phone as a different user perhaps? … or better yet, let me see what I can find and you work on other issues

**Comment by GregTurner** [comment]
moving on.  btw I'll send you another drop that will make your testing
easier.

**Comment by GregTurner** [comment]
I was testing something else when I noticed I could enroll directly when using my *.local servers...

**Comment by GregTurner** [comment]
Dick reported fixed.
