### ISSUE TITLE
authorizations not displayed in Agent's Review Authorizations UI

### ISSUE THREAD

**Issue by GregTurner** [dickhardt/A2P3_agent#38]
tracing...

**Comment by GregTurner** [comment]
I seem to be getting {"result":{}}  from registrar...

**Comment by dickhardt** [comment]
context?

What did you do? If this is filed for your own tracking, that is ok. Otherwise I have no clue on what is going on.

**Comment by GregTurner** [comment]
fixed.  same problem as:
https://github.com/dickhardt/A2P3_agent/issues/39
