### ISSUE TITLE
Authorization prompt

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#42]
"Clinic is requesting:"

"Clinic requests:"

The font should probably be a little smaller for this title so that apps with longer names will work easily.

Also, would be nice if the buttons were larger and  said

[Cancel]      [Authorize]

**Comment by GregTurner** [comment]
I was in there so I made this change... but...  now we have two buttons called Cancel.  And, I do respond differently to the CLinet APp if they cancel vs not authorized

**Comment by GregTurner** [comment]
Did 'Deny' instead of Cancel because they are two different response to client.

**Comment by GregTurner** [comment]
done
