### ISSUE TITLE
Agent does not fail transaction when it has an INVALID_TOKEN

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#46]
If the Agent was registered against an earlier DB of the A2P3 servers, it will no longer have a valid token and potentially device. 

When calling Registrar /request/verify the Agent will get the following error:

INVALID_TOKEN   unrecognized agent token

The Agent should alert the User and abort the transaction.

**Comment by GregTurner** [comment]
That was intentional to be tolerant while the bugs are shaked out.  This is a good time to start tightening the screws.

**Comment by dickhardt** [comment]
Ok. Differentiate between this failure and the verify failure. This failure indicates the Agent is misconfigured.

**Comment by GregTurner** [comment]
Are you using INVALID_DEVICEID as well?

**Comment by GregTurner** [comment]
should work, not fully test
