### ISSUE TITLE
Agent is not sending state back

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#48]
open bank app
Open an Account -> QR code comes up
Scan QR code
bank sends result below
Agent does NOT send state parameter back in get to returnURL, only sends token and request

 { result: 
   { agentRequest: 'eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiIsImtpZCI6Im5uWUdESnZLXzZWZUFBQ0wifQ.eyJpc3MiOiJiYW5rLmRldi5hMnAzLm5ldCIsImF1ZCI6Iml4LmRldi5hMnAzLm5ldCIsImlhdCI6MTM1OTczODk5NiwicmVxdWVzdC5hMnAzLm9yZyI6eyJyZXNvdXJjZXMiOlsiaHR0cDovL3Blb3BsZS5kZXYuYTJwMy5uZXQvc2NvcGUvZGV0YWlscyIsImh0dHA6Ly9zaS5kZXYuYTJwMy5uZXQvc2NvcGUvYW55dGltZS9udW1iZXIiXSwiYXV0aCI6eyJwYXNzY29kZSI6dHJ1ZSwiYXV0aG9yaXphdGlvbiI6dHJ1ZX0sInJldHVyblVSTCI6Imh0dHA6Ly9iYW5rLmRldi5hMnAzLm5ldC9yZXNwb25zZSJ9fQ.4R9WlmtK9gARB4miX7mJ9XhfedaMd1TS8bS4b8lVaPQ66yiojyC6wstiYu-X9IS_W4aqTnQx1ejhlpDwiZDCMQ',
     state: '3b1TuMvY4dVH8PzfPp6FLQ' } }

**Comment by GregTurner** [comment]
fixed.  want a agent drop?

**Comment by dickhardt** [comment]
Would you add in:

https://github.com/dickhardt/A2P3_agent/issues/45

So I don't have to try and add '.dev' to the right place in three edit lines on the tiny screen?

Reconfiguring the agent each time is a pain

Rather than having the full URL, just have a drop down of the three different root domains

**Comment by GregTurner** [comment]
sure
