### ISSUE TITLE
Agent prompts for release of no data

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#49]
When scanning QR code on Bank after clicking Login 
Agent prompts with sceeen 

There should be no prompt when there are no resources being requested

![IMG_0970](https://f.cloud.github.com/assets/688982/119049/f79d0a4e-6c94-11e2-8804-e11d6076ebdc.PNG)

**Comment by GregTurner** [comment]
I think we should discuss the ux on this one.  If the user is expecting to always authorize and view the name of the client app.  I had a previous issue open to provide a better message.

**Comment by dickhardt** [comment]
Show the name of the App in the Passcode prompt so the User knows why they are typing in their passcode. You can also list how many resources are being requested in that screen or some such. An extra click through to confirm you authorize the App to not ask for anything is sub optimal.

**Comment by GregTurner** [comment]
Cache App Name for quick display.

**Comment by GregTurner** [comment]
done
