### ISSUE TITLE
authz button needs to be pushed twice.

### ISSUE THREAD

**Issue by GregTurner** [dickhardt/A2P3_agent#50]

**Comment by dickhardt** [comment]
Don't know if it is twice. It might be that the event is not being listened to in time. Or there is a long delay before the screen changes

**Comment by GregTurner** [comment]
fixed

**Comment by GregTurner** [comment]
maybe not... it seems to only affect QR requests...

**Comment by GregTurner** [comment]
fixed!  jquery click event sometimes doesn't fire my event.  changed to listening for tap.
