### ISSUE TITLE
Running App from Demo link on Agent has Agent stuck at Demo page

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#54]
Open Agent
Click "Demo Apps'
Cick "Demo Apps" button - not sure why this step is there, we should launch Safari to Demo Apps directly

Click Bank
End up in Agent on page where can only click "Demo Apps" button

....

tried reproducing, could not reproduce when went back, perhaps a first run through state issue?

**Comment by dickhardt** [comment]
Reproduced again on first time through.

**Comment by GregTurner** [comment]
n/a since we go direct now
