### ISSUE TITLE
Extrastep in getting to Demo apps - remove?

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#55]

**Comment by GregTurner** [comment]
I was thinking the same thing.

**Comment by GregTurner** [comment]
Hmmm... maybe keep it if we want to go direct to Bank Phone App

**Comment by dickhardt** [comment]
We can have a link to download the Bank Phone app on the Landing page as well.

**Comment by GregTurner** [comment]
alright, lets get rid of it.

**Comment by GregTurner** [comment]
done
