### ISSUE TITLE
touch responses latency

### ISSUE THREAD

**Issue by GregTurner** [dickhardt/A2P3_agent#6]
Browser click events are too slow in iPhone device making the pin pad noticably slow.  This is a widely known issue.  Several solution include google fast button or a simple touch start event.

http://floatlearning.com/2011/03/developing-better-phonegap-apps/

**Comment by dickhardt** [comment]
ouch …

**Comment by GregTurner** [comment]
Yes feel my pain.  My architecture was all roses until now.  Not to worry, I have an ace in the hole.  I can always break into a native control.

**Comment by GregTurner** [comment]
Timing JS code on iPhone show handling key press is < 10ms. 

Using $.mobile.buttonMarkup.hoverDelay = 0;
helps visual appearance only.

**Comment by GregTurner** [comment]
fixed, near native performance!  improves overall performance not just pin pad.

thanks fastclick!
https://github.com/ftlabs/fastclick
