### ISSUE TITLE
Check that ix property is correct in Agent Request

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#82]
There is a new attribute to state which IX is being used (the protocol scheme for the IX) -- this is needed so that the Agent knows which IX the App wants to talk to when a QR code is scanned as the IX. Since the Agent is not being invoked via  a protocol handler, the Agent needs an indicator of which IX for a multi IX system.

['request.a2p3.net'].ix = 'a2p3.net'

**Comment by GregTurner** [comment]
the jwt already has the ix in the AUD parameter, e.g., "aud": "ix.a2p3.net".  Or is that not the same thing?

**Comment by dickhardt** [comment]
Changed spec and pivoted on how multiple IXes are handled
