### ISSUE TITLE
Agent not sending notificationURL parameter to AS

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#86]
I send the following back when the shortURL is called:

{ result: 
   { agentRequest: 'eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzUxMiIsImtpZCI6IjJTQjhjbmNpLVJlZXJCVC0ifQ.eyJpc3MiOiJsb2NhbC5leGFtcGxlLmNvbSIsImF1ZCI6Iml4LmRldi5hMnAzLm5ldCIsImlhdCI6MTM2MjY4NDQ5NSwicmVxdWVzdC5hMnAzLm9yZyI6eyJyZXNvdXJjZXMiOlsiaHR0cDovL2VtYWlsLmRldi5hMnAzLm5ldC9zY29wZS9kZWZhdWx0IiwiaHR0cDovL3Blb3BsZS5kZXYuYTJwMy5uZXQvc2NvcGUvZGV0YWlscyIsImh0dHA6Ly9zaS5kZXYuYTJwMy5uZXQvc2NvcGUvbnVtYmVyIiwiaHR0cDovL2hlYWx0aC5kZXYuYTJwMy5uZXQvc2NvcGUvcHJvdl9udW1iZXIiXSwiYXV0aCI6eyJwYXNzY29kZSI6dHJ1ZSwiYXV0aG9yaXphdGlvbiI6dHJ1ZX0sIml4IjoiYTJwMy5uZXQiLCJjYWxsYmFja1VSTCI6Imh0dHA6Ly9tYWNwcm8ubG9jYWw6ODA4MC9yZXNwb25zZS9jYWxsYmFjayJ9fQ.ymU6DID5BS_r8m7CVielBhbFkX7-oPf7YdFXqI6SdUlIQoe4-vPQtksHdcMCMLdomwRysgHyft7S7-XDw7j2qw',
     state: 'refEh0cL_L6szp0AO-yqFA',
     notificationURL: true } }

But this is what the Agent sends me:

 { device: '4c49c49e-5676-f509-93d3-87ded0667760',
  sar: 'ymU6DID5BS_r8m7CVielBhbFkX7-oPf7YdFXqI6SdUlIQoe4-vPQtksHdcMCMLdomwRysgHyft7S7-XDw7j2qw',
  auth: { passcode: '1111', authorization: true } }

**Comment by GregTurner** [comment]
fixed, new Agent coming in the morning.
