### ISSUE TITLE
Authorize button shows up before all authorization text has been displayed

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#87]
This is more noticable on slow links. The scopes appear slowly, and user may not see all scopes before authorizing. All scopes MUST be shown before user can authorize. If an scope retrieval fails, then error must be shown and user MUST not be presented with a anuthorize button.

Perhaps show "retrieving authorization requests ..." until all have been retrieved.

**Comment by GregTurner** [comment]
done
