### ISSUE TITLE
intermediate pages showing when notification comes in

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#98]
I briefly see some intermediate pages when dealing with a notification. Not sure if it happens in other authorizations, but do see it with the notifications. Please test on a slow machine to determine what is going on.

**Comment by GregTurner** [comment]
The intermediate page is the home page right?

**Comment by dickhardt** [comment]
I don't know … it comes in and out fast … you will have it soon to test on a slow iOS device

**Comment by GregTurner** [comment]
This is a duplicate issue I've already noticed, even on the iPhone 5.

**Comment by dickhardt** [comment]
It is different than the other one.

**Comment by GregTurner** [comment]
Timing tests reveal that if there are no pending notifications checking for them costs 15ms.  If there are pending notifications its 250ms.  Serializing async call to get notifications shouldn't be noticeable when launching without notifications.

**Comment by dickhardt** [comment]
Please make sure you test on a slow machine!

**Comment by GregTurner** [comment]
iPhone 4 takes 100ms without pending notifications.  And, 1000ms with a pending notification.

**Comment by GregTurner** [comment]
done

**Comment by dickhardt** [comment]
A full second to respond is REALLY long.

**Comment by GregTurner** [comment]
I know!  The lag is somewhere in either my plugin and/or iOS. From the
timing evidence it may be related to CPU and not some inherent network lag.
