### ISSUE TITLE
fixup layout in registry dashboard

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#99]
see dashboard_registrar.html

layout in popup from Register Application and in App Details needs to be fixed up to deal with new Anytime field

**Comment by GregTurner** [comment]
wrong repo Dick?

**Comment by dickhardt** [comment]
oops, sorry -- should be in A2P3_HTML

On Tue, Mar 12, 2013 at 6:31 AM, GregTurner notifications@github.comwrote:

> wrong repo Dick?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dickhardt/A2P3_agent/issues/99#issuecomment-14774915
> .

## 

-- Dick

**Comment by GregTurner** [comment]
moved.
